# This is a basic workflow to help you get started with Actions

name: azure bicep deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_RESOURCEGROUP_NAME: demo-rg
  ENVIRONMENT_LOCATION: EastUS

jobs:
  lint_Sanity_Check:
    name: Sanity check using lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: |
        bicep build --stdout ./actions/bicep/storage.bicep | bicep validate
        
  syntax_check:
    name: Syntax check using bicep validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./actions/bicep/storage.bicep
        parameters: location=${{ env.ENVIRONMENT_LOCATION }}
        deploymentMode: Validate

  validate_changes:
    name: Validate changes using bicep what-if
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [lint_Sanity_Check, syntax_check]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: 'deploy storage account bicep'
        working-directory: '${{github.workspace}}/actions/bicep'
        run: |
          az deployment group create --what-if --resource-group demo-rg --template-file './storage.bicep' --parameters @parameters.json

  deploy:
    runs-on: ubuntu-latest
    needs: [lint_Sanity_Check, syntax_check, validate_changes]
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
    - uses: azure/arm-deploy@v1
      name: Deploy storage account
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./actions/bicep/storage.bicep
        parameters: location=${{ env.ENVIRONMENT_LOCATION}}
